# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.mission_queue_api import MissionQueueApi  # noqa: E501
from mir.rest import ApiException


class TestMissionQueueApi(unittest.TestCase):
    """MissionQueueApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.mission_queue_api.MissionQueueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mission_queue_delete(self):
        """Test case for mission_queue_delete

        DELETE /mission_queue  # noqa: E501
        """
        pass

    def test_mission_queue_get(self):
        """Test case for mission_queue_get

        GET /mission_queue  # noqa: E501
        """
        pass

    def test_mission_queue_id_delete(self):
        """Test case for mission_queue_id_delete

        DELETE /mission_queue/{id}  # noqa: E501
        """
        pass

    def test_mission_queue_id_get(self):
        """Test case for mission_queue_id_get

        GET /mission_queue/{id}  # noqa: E501
        """
        pass

    def test_mission_queue_id_put(self):
        """Test case for mission_queue_id_put

        PUT /mission_queue/{id}  # noqa: E501
        """
        pass

    def test_mission_queue_mission_queue_id_actions_get(self):
        """Test case for mission_queue_mission_queue_id_actions_get

        GET /mission_queue/{mission_queue_id}/actions  # noqa: E501
        """
        pass

    def test_mission_queue_mission_queue_id_actions_id_get(self):
        """Test case for mission_queue_mission_queue_id_actions_id_get

        GET /mission_queue/{mission_queue_id}/actions/{id}  # noqa: E501
        """
        pass

    def test_mission_queue_post(self):
        """Test case for mission_queue_post

        POST /mission_queue  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
