# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.system_status_api import SystemStatusApi  # noqa: E501
from mir.rest import ApiException


class TestSystemStatusApi(unittest.TestCase):
    """SystemStatusApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.system_status_api.SystemStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_software_system_status_get(self):
        """Test case for software_system_status_get

        GET /software/system_status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
