# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.position_types_api import PositionTypesApi  # noqa: E501
from mir.rest import ApiException


class TestPositionTypesApi(unittest.TestCase):
    """PositionTypesApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.position_types_api.PositionTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_position_types_get(self):
        """Test case for position_types_get

        GET /position_types  # noqa: E501
        """
        pass

    def test_position_types_id_get(self):
        """Test case for position_types_id_get

        GET /position_types/{id}  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
