# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.export_api import ExportApi  # noqa: E501
from mir.rest import ApiException


class TestExportApi(unittest.TestCase):
    """ExportApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.export_api.ExportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hw_export_get(self):
        """Test case for hw_export_get

        GET /hw/export  # noqa: E501
        """
        pass

    def test_sessions_guid_export_get(self):
        """Test case for sessions_guid_export_get

        GET /sessions/{guid}/export  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
