# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.users_api import UsersApi  # noqa: E501
from mir.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_auth_delete(self):
        """Test case for users_auth_delete

        DELETE /users/auth  # noqa: E501
        """
        pass

    def test_users_auth_post(self):
        """Test case for users_auth_post

        POST /users/auth  # noqa: E501
        """
        pass

    def test_users_get(self):
        """Test case for users_get

        GET /users  # noqa: E501
        """
        pass

    def test_users_guid_delete(self):
        """Test case for users_guid_delete

        DELETE /users/{guid}  # noqa: E501
        """
        pass

    def test_users_guid_get(self):
        """Test case for users_guid_get

        GET /users/{guid}  # noqa: E501
        """
        pass

    def test_users_guid_put(self):
        """Test case for users_guid_put

        PUT /users/{guid}  # noqa: E501
        """
        pass

    def test_users_me_get(self):
        """Test case for users_me_get

        GET /users/me  # noqa: E501
        """
        pass

    def test_users_me_group_get(self):
        """Test case for users_me_group_get

        GET /users/me/group  # noqa: E501
        """
        pass

    def test_users_me_permissions_get(self):
        """Test case for users_me_permissions_get

        GET /users/me/permissions  # noqa: E501
        """
        pass

    def test_users_me_put(self):
        """Test case for users_me_put

        PUT /users/me  # noqa: E501
        """
        pass

    def test_users_post(self):
        """Test case for users_post

        POST /users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
