# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.models.post_cert import PostCert  # noqa: E501
from mir.rest import ApiException


class TestPostCert(unittest.TestCase):
    """PostCert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostCert(self):
        """Test PostCert"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mir.models.post_cert.PostCert()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
