# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.models.get_io_module import GetIoModule  # noqa: E501
from mir.rest import ApiException


class TestGetIoModule(unittest.TestCase):
    """GetIoModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetIoModule(self):
        """Test GetIoModule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mir.models.get_io_module.GetIoModule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
