# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.log_api import LogApi  # noqa: E501
from mir.rest import ApiException


class TestLogApi(unittest.TestCase):
    """LogApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.log_api.LogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_log_error_reports_delete(self):
        """Test case for log_error_reports_delete

        DELETE /log/error_reports  # noqa: E501
        """
        pass

    def test_log_error_reports_get(self):
        """Test case for log_error_reports_get

        GET /log/error_reports  # noqa: E501
        """
        pass

    def test_log_error_reports_id_delete(self):
        """Test case for log_error_reports_id_delete

        DELETE /log/error_reports/{id}  # noqa: E501
        """
        pass

    def test_log_error_reports_id_download_get(self):
        """Test case for log_error_reports_id_download_get

        GET /log/error_reports/{id}/download  # noqa: E501
        """
        pass

    def test_log_error_reports_id_get(self):
        """Test case for log_error_reports_id_get

        GET /log/error_reports/{id}  # noqa: E501
        """
        pass

    def test_log_error_reports_post(self):
        """Test case for log_error_reports_post

        POST /log/error_reports  # noqa: E501
        """
        pass

    def test_remote_support_log_get(self):
        """Test case for remote_support_log_get

        GET /remote_support/log  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
