# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.elevator_floors_api import ElevatorFloorsApi  # noqa: E501
from mir.rest import ApiException


class TestElevatorFloorsApi(unittest.TestCase):
    """ElevatorFloorsApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.elevator_floors_api.ElevatorFloorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_elevator_floors_get(self):
        """Test case for elevator_floors_get

        GET /elevator_floors  # noqa: E501
        """
        pass

    def test_elevator_floors_guid_delete(self):
        """Test case for elevator_floors_guid_delete

        DELETE /elevator_floors/{guid}  # noqa: E501
        """
        pass

    def test_elevator_floors_guid_get(self):
        """Test case for elevator_floors_guid_get

        GET /elevator_floors/{guid}  # noqa: E501
        """
        pass

    def test_elevator_floors_guid_put(self):
        """Test case for elevator_floors_guid_put

        PUT /elevator_floors/{guid}  # noqa: E501
        """
        pass

    def test_elevator_floors_post(self):
        """Test case for elevator_floors_post

        POST /elevator_floors  # noqa: E501
        """
        pass

    def test_sessions_session_id_elevator_floors_get(self):
        """Test case for sessions_session_id_elevator_floors_get

        GET /sessions/{session_id}/elevator_floors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
