# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.download_api import DownloadApi  # noqa: E501
from mir.rest import ApiException


class TestDownloadApi(unittest.TestCase):
    """DownloadApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.download_api.DownloadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_log_error_reports_id_download_get(self):
        """Test case for log_error_reports_id_download_get

        GET /log/error_reports/{id}/download  # noqa: E501
        """
        pass

    def test_system_setup_sick_configs_guid_download_get(self):
        """Test case for system_setup_sick_configs_guid_download_get

        GET /system/setup/sick_configs/{guid}/download  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
