# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mir
from mir.api.actions_api import ActionsApi  # noqa: E501
from mir.rest import ApiException


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self):
        self.api = mir.api.actions_api.ActionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_actions_action_type_get(self):
        """Test case for actions_action_type_get

        GET /actions/{action_type}  # noqa: E501
        """
        pass

    def test_actions_action_type_post(self):
        """Test case for actions_action_type_post

        POST /actions/{action_type}  # noqa: E501
        """
        pass

    def test_actions_get(self):
        """Test case for actions_get

        GET /actions  # noqa: E501
        """
        pass

    def test_mission_groups_mission_group_id_actions_get(self):
        """Test case for mission_groups_mission_group_id_actions_get

        GET /mission_groups/{mission_group_id}/actions  # noqa: E501
        """
        pass

    def test_mission_queue_mission_queue_id_actions_get(self):
        """Test case for mission_queue_mission_queue_id_actions_get

        GET /mission_queue/{mission_queue_id}/actions  # noqa: E501
        """
        pass

    def test_mission_queue_mission_queue_id_actions_id_get(self):
        """Test case for mission_queue_mission_queue_id_actions_id_get

        GET /mission_queue/{mission_queue_id}/actions/{id}  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_get(self):
        """Test case for missions_mission_id_actions_get

        GET /missions/{mission_id}/actions  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_guid_delete(self):
        """Test case for missions_mission_id_actions_guid_delete

        DELETE /missions/{mission_id}/actions/{guid}  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_guid_get(self):
        """Test case for missions_mission_id_actions_guid_get

        GET /missions/{mission_id}/actions/{guid}  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_guid_put(self):
        """Test case for missions_mission_id_actions_guid_put

        PUT /missions/{mission_id}/actions/{guid}  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_post(self):
        """Test case for missions_mission_id_actions_post

        POST /missions/{mission_id}/actions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
