version: '3.8'

services:
  swagger-codegen:
    image: swaggerapi/swagger-codegen-cli
    volumes:
      - /home/robot-ranger/development/process-robotics/tmp/mir-api:/local
    # command: ls -la
    command: generate -i /local/swagger.json -l python -o /local -DpackageName=mir