from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from mir.api.action_definitions_api import ActionDefinitionsApi
from mir.api.actions_api import ActionsApi
from mir.api.advanced_api import AdvancedApi
from mir.api.auth_api import AuthApi
from mir.api.backups_api import BackupsApi
from mir.api.brake_api import BrakeApi
from mir.api.cameras_api import CamerasApi
from mir.api.cart_calibrations_api import CartCalibrationsApi
from mir.api.cart_types_api import CartTypesApi
from mir.api.carts_api import CartsApi
from mir.api.cert_api import CertApi
from mir.api.clear_site_data_api import ClearSiteDataApi
from mir.api.connections_api import ConnectionsApi
from mir.api.dashboards_api import DashboardsApi
from mir.api.definition_api import DefinitionApi
from mir.api.definitions_api import DefinitionsApi
from mir.api.diagnostics_api import DiagnosticsApi
from mir.api.distance_api import DistanceApi
from mir.api.docking_offsets_api import DockingOffsetsApi
from mir.api.download_api import DownloadApi
from mir.api.elevator_floors_api import ElevatorFloorsApi
from mir.api.elevators_api import ElevatorsApi
from mir.api.error_reports_api import ErrorReportsApi
from mir.api.experimental_api import ExperimentalApi
from mir.api.export_api import ExportApi
from mir.api.external_interfaces_api import ExternalInterfacesApi
from mir.api.factory_reset_api import FactoryResetApi
from mir.api.footprints_api import FootprintsApi
from mir.api.gripper_api import GripperApi
from mir.api.group_api import GroupApi
from mir.api.height_api import HeightApi
from mir.api.helper_positions_api import HelperPositionsApi
from mir.api.hook_api import HookApi
from mir.api.hook_interface_api import HookInterfaceApi
from mir.api.hw_api import HwApi
from mir.api.import_api import ImportApi
from mir.api.info_api import InfoApi
from mir.api.io_modules_api import IoModulesApi
from mir.api.lasers_api import LasersApi
from mir.api.log_api import LogApi
from mir.api.logs_api import LogsApi
from mir.api.maps_api import MapsApi
from mir.api.me_api import MeApi
from mir.api.metrics_api import MetricsApi
from mir.api.mission_groups_api import MissionGroupsApi
from mir.api.mission_queue_api import MissionQueueApi
from mir.api.missions_api import MissionsApi
from mir.api.modbus_api import ModbusApi
from mir.api.motor_controllers_api import MotorControllersApi
from mir.api.networks_api import NetworksApi
from mir.api.options_api import OptionsApi
from mir.api.path_guides_api import PathGuidesApi
from mir.api.path_guides_positions_api import PathGuidesPositionsApi
from mir.api.path_guides_precalc_api import PathGuidesPrecalcApi
from mir.api.paths_api import PathsApi
from mir.api.permissions_api import PermissionsApi
from mir.api.platform_api import PlatformApi
from mir.api.position_transition_lists_api import PositionTransitionListsApi
from mir.api.position_types_api import PositionTypesApi
from mir.api.positions_api import PositionsApi
from mir.api.protective_scan_api import ProtectiveScanApi
from mir.api.record_api import RecordApi
from mir.api.registers_api import RegistersApi
from mir.api.remote_support_api import RemoteSupportApi
from mir.api.robot_peripherals_status_api import RobotPeripheralsStatusApi
from mir.api.robots_api import RobotsApi
from mir.api.serial_devices_api import SerialDevicesApi
from mir.api.service_book_api import ServiceBookApi
from mir.api.sessions_api import SessionsApi
from mir.api.setting_groups_api import SettingGroupsApi
from mir.api.settings_api import SettingsApi
from mir.api.setup_api import SetupApi
from mir.api.shelfs_api import ShelfsApi
from mir.api.sick_configs_api import SickConfigsApi
from mir.api.software_api import SoftwareApi
from mir.api.sounds_api import SoundsApi
from mir.api.ssl_api import SslApi
from mir.api.statistics_api import StatisticsApi
from mir.api.status_api import StatusApi
from mir.api.stream_api import StreamApi
from mir.api.swagger_api import SwaggerApi
from mir.api.system_api import SystemApi
from mir.api.system_status_api import SystemStatusApi
from mir.api.timezone_api import TimezoneApi
from mir.api.types_api import TypesApi
from mir.api.upgrades_api import UpgradesApi
from mir.api.uploads_api import UploadsApi
from mir.api.user_groups_api import UserGroupsApi
from mir.api.users_api import UsersApi
from mir.api.widgets_api import WidgetsApi
from mir.api.wifi_api import WifiApi
from mir.api.world_model_api import WorldModelApi
from mir.api.zones_api import ZonesApi
