# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mir.configuration import Configuration


class GetSoftwareBackups(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'guid': 'str',
        'state': 'str',
        'version': 'str',
        '_date': 'datetime'
    }

    attribute_map = {
        'url': 'url',
        'guid': 'guid',
        'state': 'state',
        'version': 'version',
        '_date': 'date'
    }

    def __init__(self, url=None, guid=None, state=None, version=None, _date=None, _configuration=None):  # noqa: E501
        """GetSoftwareBackups - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._url = None
        self._guid = None
        self._state = None
        self._version = None
        self.__date = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if guid is not None:
            self.guid = guid
        if state is not None:
            self.state = state
        if version is not None:
            self.version = version
        if _date is not None:
            self._date = _date

    @property
    def url(self):
        """Gets the url of this GetSoftwareBackups.  # noqa: E501

        The URL of the resource  # noqa: E501

        :return: The url of this GetSoftwareBackups.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GetSoftwareBackups.

        The URL of the resource  # noqa: E501

        :param url: The url of this GetSoftwareBackups.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def guid(self):
        """Gets the guid of this GetSoftwareBackups.  # noqa: E501

        The guid of the software backup  # noqa: E501

        :return: The guid of this GetSoftwareBackups.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this GetSoftwareBackups.

        The guid of the software backup  # noqa: E501

        :param guid: The guid of this GetSoftwareBackups.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def state(self):
        """Gets the state of this GetSoftwareBackups.  # noqa: E501

        The state of the software backup  # noqa: E501

        :return: The state of this GetSoftwareBackups.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GetSoftwareBackups.

        The state of the software backup  # noqa: E501

        :param state: The state of this GetSoftwareBackups.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def version(self):
        """Gets the version of this GetSoftwareBackups.  # noqa: E501

        The version of the software backup  # noqa: E501

        :return: The version of this GetSoftwareBackups.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this GetSoftwareBackups.

        The version of the software backup  # noqa: E501

        :param version: The version of this GetSoftwareBackups.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def _date(self):
        """Gets the _date of this GetSoftwareBackups.  # noqa: E501

        The date where the backup was created  # noqa: E501

        :return: The _date of this GetSoftwareBackups.  # noqa: E501
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this GetSoftwareBackups.

        The date where the backup was created  # noqa: E501

        :param _date: The _date of this GetSoftwareBackups.  # noqa: E501
        :type: datetime
        """

        self.__date = _date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSoftwareBackups, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSoftwareBackups):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetSoftwareBackups):
            return True

        return self.to_dict() != other.to_dict()
