# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mir.configuration import Configuration


class GetHook(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'available': 'bool',
        'brake': 'GetHookBrake1',
        'angle': 'float',
        'gripper': 'GetHookGripper1',
        'height': 'GetHookHeight1'
    }

    attribute_map = {
        'available': 'available',
        'brake': 'brake',
        'angle': 'angle',
        'gripper': 'gripper',
        'height': 'height'
    }

    def __init__(self, available=None, brake=None, angle=None, gripper=None, height=None, _configuration=None):  # noqa: E501
        """GetHook - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._available = None
        self._brake = None
        self._angle = None
        self._gripper = None
        self._height = None
        self.discriminator = None

        if available is not None:
            self.available = available
        if brake is not None:
            self.brake = brake
        if angle is not None:
            self.angle = angle
        if gripper is not None:
            self.gripper = gripper
        if height is not None:
            self.height = height

    @property
    def available(self):
        """Gets the available of this GetHook.  # noqa: E501

        Whether the hook data is available or not  # noqa: E501

        :return: The available of this GetHook.  # noqa: E501
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this GetHook.

        Whether the hook data is available or not  # noqa: E501

        :param available: The available of this GetHook.  # noqa: E501
        :type: bool
        """

        self._available = available

    @property
    def brake(self):
        """Gets the brake of this GetHook.  # noqa: E501


        :return: The brake of this GetHook.  # noqa: E501
        :rtype: GetHookBrake1
        """
        return self._brake

    @brake.setter
    def brake(self, brake):
        """Sets the brake of this GetHook.


        :param brake: The brake of this GetHook.  # noqa: E501
        :type: GetHookBrake1
        """

        self._brake = brake

    @property
    def angle(self):
        """Gets the angle of this GetHook.  # noqa: E501

        The angle of the hook arm  # noqa: E501

        :return: The angle of this GetHook.  # noqa: E501
        :rtype: float
        """
        return self._angle

    @angle.setter
    def angle(self, angle):
        """Sets the angle of this GetHook.

        The angle of the hook arm  # noqa: E501

        :param angle: The angle of this GetHook.  # noqa: E501
        :type: float
        """

        self._angle = angle

    @property
    def gripper(self):
        """Gets the gripper of this GetHook.  # noqa: E501


        :return: The gripper of this GetHook.  # noqa: E501
        :rtype: GetHookGripper1
        """
        return self._gripper

    @gripper.setter
    def gripper(self, gripper):
        """Sets the gripper of this GetHook.


        :param gripper: The gripper of this GetHook.  # noqa: E501
        :type: GetHookGripper1
        """

        self._gripper = gripper

    @property
    def height(self):
        """Gets the height of this GetHook.  # noqa: E501


        :return: The height of this GetHook.  # noqa: E501
        :rtype: GetHookHeight1
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this GetHook.


        :param height: The height of this GetHook.  # noqa: E501
        :type: GetHookHeight1
        """

        self._height = height

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetHook, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetHook):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetHook):
            return True

        return self.to_dict() != other.to_dict()
