# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mir.configuration import Configuration


class GetSetupCameras(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'camera_model': 'str',
        'camera_position': 'str',
        'value': 'str'
    }

    attribute_map = {
        'url': 'url',
        'camera_model': 'camera_model',
        'camera_position': 'camera_position',
        'value': 'value'
    }

    def __init__(self, url=None, camera_model=None, camera_position=None, value=None, _configuration=None):  # noqa: E501
        """GetSetupCameras - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._url = None
        self._camera_model = None
        self._camera_position = None
        self._value = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if camera_model is not None:
            self.camera_model = camera_model
        if camera_position is not None:
            self.camera_position = camera_position
        if value is not None:
            self.value = value

    @property
    def url(self):
        """Gets the url of this GetSetupCameras.  # noqa: E501

        The URL of the resource  # noqa: E501

        :return: The url of this GetSetupCameras.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GetSetupCameras.

        The URL of the resource  # noqa: E501

        :param url: The url of this GetSetupCameras.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def camera_model(self):
        """Gets the camera_model of this GetSetupCameras.  # noqa: E501

          # noqa: E501

        :return: The camera_model of this GetSetupCameras.  # noqa: E501
        :rtype: str
        """
        return self._camera_model

    @camera_model.setter
    def camera_model(self, camera_model):
        """Sets the camera_model of this GetSetupCameras.

          # noqa: E501

        :param camera_model: The camera_model of this GetSetupCameras.  # noqa: E501
        :type: str
        """

        self._camera_model = camera_model

    @property
    def camera_position(self):
        """Gets the camera_position of this GetSetupCameras.  # noqa: E501

          # noqa: E501

        :return: The camera_position of this GetSetupCameras.  # noqa: E501
        :rtype: str
        """
        return self._camera_position

    @camera_position.setter
    def camera_position(self, camera_position):
        """Sets the camera_position of this GetSetupCameras.

          # noqa: E501

        :param camera_position: The camera_position of this GetSetupCameras.  # noqa: E501
        :type: str
        """

        self._camera_position = camera_position

    @property
    def value(self):
        """Gets the value of this GetSetupCameras.  # noqa: E501

          # noqa: E501

        :return: The value of this GetSetupCameras.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this GetSetupCameras.

          # noqa: E501

        :param value: The value of this GetSetupCameras.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetSetupCameras, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetSetupCameras):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetSetupCameras):
            return True

        return self.to_dict() != other.to_dict()
