# coding: utf-8

"""
    3.5.4 MIR250 REST API

    The REST API for the 3.5.4 interface of MIR250  # noqa: E501

    OpenAPI spec version: 3.5.4
    Contact: support@mir-robots.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mir.configuration import Configuration


class PutUserGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'session_expiration_enabled': 'bool',
        'session_timeout': 'int'
    }

    attribute_map = {
        'name': 'name',
        'session_expiration_enabled': 'session_expiration_enabled',
        'session_timeout': 'session_timeout'
    }

    def __init__(self, name=None, session_expiration_enabled=None, session_timeout=None, _configuration=None):  # noqa: E501
        """PutUserGroup - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._session_expiration_enabled = None
        self._session_timeout = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if session_expiration_enabled is not None:
            self.session_expiration_enabled = session_expiration_enabled
        if session_timeout is not None:
            self.session_timeout = session_timeout

    @property
    def name(self):
        """Gets the name of this PutUserGroup.  # noqa: E501

        Min length: 2, Max length: 255  # noqa: E501

        :return: The name of this PutUserGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PutUserGroup.

        Min length: 2, Max length: 255  # noqa: E501

        :param name: The name of this PutUserGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def session_expiration_enabled(self):
        """Gets the session_expiration_enabled of this PutUserGroup.  # noqa: E501


        :return: The session_expiration_enabled of this PutUserGroup.  # noqa: E501
        :rtype: bool
        """
        return self._session_expiration_enabled

    @session_expiration_enabled.setter
    def session_expiration_enabled(self, session_expiration_enabled):
        """Sets the session_expiration_enabled of this PutUserGroup.


        :param session_expiration_enabled: The session_expiration_enabled of this PutUserGroup.  # noqa: E501
        :type: bool
        """

        self._session_expiration_enabled = session_expiration_enabled

    @property
    def session_timeout(self):
        """Gets the session_timeout of this PutUserGroup.  # noqa: E501


        :return: The session_timeout of this PutUserGroup.  # noqa: E501
        :rtype: int
        """
        return self._session_timeout

    @session_timeout.setter
    def session_timeout(self, session_timeout):
        """Sets the session_timeout of this PutUserGroup.


        :param session_timeout: The session_timeout of this PutUserGroup.  # noqa: E501
        :type: int
        """

        self._session_timeout = session_timeout

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutUserGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutUserGroup):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PutUserGroup):
            return True

        return self.to_dict() != other.to_dict()
